/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LiveRouteImport } from './routes/live'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as PointablesRouteImport } from './routes/pointables'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as ScorecardsRouteImport } from './routes/scorecards'
import { Route as ScorerRouteImport } from './routes/scorer'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as MatchMatchIdRouteImport } from './routes/match/$matchId'
import { Route as ObsIndexRouteImport } from './routes/obs/index'
import { Route as PlayerPlayerIdRouteImport } from './routes/player/$playerId'
import { Route as PlayersPlayerIdRouteImport } from './routes/players/$playerId'
import { Route as ScorecardMatchIdRouteImport } from './routes/scorecard/$matchId'
import { Route as ObsMatchMatchIdRouteImport } from './routes/obs/match/$matchId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const PointablesRoute = PointablesRouteImport.update({
  id: '/pointables',
  path: '/pointables',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ScorecardsRoute = ScorecardsRouteImport.update({
  id: '/scorecards',
  path: '/scorecards',
  getParentRoute: () => rootRouteImport,
} as any)
const ScorerRoute = ScorerRouteImport.update({
  id: '/scorer',
  path: '/scorer',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchMatchIdRoute = MatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const ObsIndexRoute = ObsIndexRouteImport.update({
  id: '/obs/',
  path: '/obs/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerPlayerIdRoute = PlayerPlayerIdRouteImport.update({
  id: '/player/$playerId',
  path: '/player/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPlayerIdRoute = PlayersPlayerIdRouteImport.update({
  id: '/players/$playerId',
  path: '/players/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ScorecardMatchIdRoute = ScorecardMatchIdRouteImport.update({
  id: '/scorecard/$matchId',
  path: '/scorecard/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const ObsMatchMatchIdRoute = ObsMatchMatchIdRouteImport.update({
  id: '/obs/match/$matchId',
  path: '/obs/match/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/home': typeof HomeRoute
  '/live': typeof LiveRoute
  '/matches': typeof MatchesRoute
  '/pointables': typeof PointablesRoute
  '/profile': typeof ProfileRoute
  '/records': typeof RecordsRoute
  '/rules': typeof RulesRoute
  '/scorecards': typeof ScorecardsRoute
  '/scorer': typeof ScorerRoute
  '/stats': typeof StatsRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/player/$playerId': typeof PlayerPlayerIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/scorecard/$matchId': typeof ScorecardMatchIdRoute
  '/obs/': typeof ObsIndexRoute
  '/obs/match/$matchId': typeof ObsMatchMatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/home': typeof HomeRoute
  '/live': typeof LiveRoute
  '/matches': typeof MatchesRoute
  '/pointables': typeof PointablesRoute
  '/profile': typeof ProfileRoute
  '/records': typeof RecordsRoute
  '/rules': typeof RulesRoute
  '/scorecards': typeof ScorecardsRoute
  '/scorer': typeof ScorerRoute
  '/stats': typeof StatsRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/player/$playerId': typeof PlayerPlayerIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/scorecard/$matchId': typeof ScorecardMatchIdRoute
  '/obs': typeof ObsIndexRoute
  '/obs/match/$matchId': typeof ObsMatchMatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/home': typeof HomeRoute
  '/live': typeof LiveRoute
  '/matches': typeof MatchesRoute
  '/pointables': typeof PointablesRoute
  '/profile': typeof ProfileRoute
  '/records': typeof RecordsRoute
  '/rules': typeof RulesRoute
  '/scorecards': typeof ScorecardsRoute
  '/scorer': typeof ScorerRoute
  '/stats': typeof StatsRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/player/$playerId': typeof PlayerPlayerIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/scorecard/$matchId': typeof ScorecardMatchIdRoute
  '/obs/': typeof ObsIndexRoute
  '/obs/match/$matchId': typeof ObsMatchMatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/home'
    | '/live'
    | '/matches'
    | '/pointables'
    | '/profile'
    | '/records'
    | '/rules'
    | '/scorecards'
    | '/scorer'
    | '/stats'
    | '/match/$matchId'
    | '/player/$playerId'
    | '/players/$playerId'
    | '/scorecard/$matchId'
    | '/obs/'
    | '/obs/match/$matchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/home'
    | '/live'
    | '/matches'
    | '/pointables'
    | '/profile'
    | '/records'
    | '/rules'
    | '/scorecards'
    | '/scorer'
    | '/stats'
    | '/match/$matchId'
    | '/player/$playerId'
    | '/players/$playerId'
    | '/scorecard/$matchId'
    | '/obs'
    | '/obs/match/$matchId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/home'
    | '/live'
    | '/matches'
    | '/pointables'
    | '/profile'
    | '/records'
    | '/rules'
    | '/scorecards'
    | '/scorer'
    | '/stats'
    | '/match/$matchId'
    | '/player/$playerId'
    | '/players/$playerId'
    | '/scorecard/$matchId'
    | '/obs/'
    | '/obs/match/$matchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  HomeRoute: typeof HomeRoute
  LiveRoute: typeof LiveRoute
  MatchesRoute: typeof MatchesRoute
  PointablesRoute: typeof PointablesRoute
  ProfileRoute: typeof ProfileRoute
  RecordsRoute: typeof RecordsRoute
  RulesRoute: typeof RulesRoute
  ScorecardsRoute: typeof ScorecardsRoute
  ScorerRoute: typeof ScorerRoute
  StatsRoute: typeof StatsRoute
  MatchMatchIdRoute: typeof MatchMatchIdRoute
  PlayerPlayerIdRoute: typeof PlayerPlayerIdRoute
  PlayersPlayerIdRoute: typeof PlayersPlayerIdRoute
  ScorecardMatchIdRoute: typeof ScorecardMatchIdRoute
  ObsIndexRoute: typeof ObsIndexRoute
  ObsMatchMatchIdRoute: typeof ObsMatchMatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pointables': {
      id: '/pointables'
      path: '/pointables'
      fullPath: '/pointables'
      preLoaderRoute: typeof PointablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scorecards': {
      id: '/scorecards'
      path: '/scorecards'
      fullPath: '/scorecards'
      preLoaderRoute: typeof ScorecardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scorer': {
      id: '/scorer'
      path: '/scorer'
      fullPath: '/scorer'
      preLoaderRoute: typeof ScorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$matchId': {
      id: '/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof MatchMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obs/': {
      id: '/obs/'
      path: '/obs'
      fullPath: '/obs/'
      preLoaderRoute: typeof ObsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$playerId': {
      id: '/player/$playerId'
      path: '/player/$playerId'
      fullPath: '/player/$playerId'
      preLoaderRoute: typeof PlayerPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$playerId': {
      id: '/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof PlayersPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scorecard/$matchId': {
      id: '/scorecard/$matchId'
      path: '/scorecard/$matchId'
      fullPath: '/scorecard/$matchId'
      preLoaderRoute: typeof ScorecardMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obs/match/$matchId': {
      id: '/obs/match/$matchId'
      path: '/obs/match/$matchId'
      fullPath: '/obs/match/$matchId'
      preLoaderRoute: typeof ObsMatchMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  HomeRoute: HomeRoute,
  LiveRoute: LiveRoute,
  MatchesRoute: MatchesRoute,
  PointablesRoute: PointablesRoute,
  ProfileRoute: ProfileRoute,
  RecordsRoute: RecordsRoute,
  RulesRoute: RulesRoute,
  ScorecardsRoute: ScorecardsRoute,
  ScorerRoute: ScorerRoute,
  StatsRoute: StatsRoute,
  MatchMatchIdRoute: MatchMatchIdRoute,
  PlayerPlayerIdRoute: PlayerPlayerIdRoute,
  PlayersPlayerIdRoute: PlayersPlayerIdRoute,
  ScorecardMatchIdRoute: ScorecardMatchIdRoute,
  ObsIndexRoute: ObsIndexRoute,
  ObsMatchMatchIdRoute: ObsMatchMatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
